FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine

RUN apk add --no-cache bash

WORKDIR /app

ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
ENV DOTNET_NOLOGO=1
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
ENV NUGET_XMLDOC_MODE=skip

COPY *.csproj ./
RUN dotnet restore

COPY . ./
